---
# port_profiles:
#   - profile: int_trunk_host
#     mode: trunk
#     vlans: "20,2300,2301"
#   - profile: int_access_host
#     mode: access
#     vlans: "2300"


# network_ports:
#   - switches:
#       - s1-leaf[1]
#     switch_ports: # Ex Ethernet1-48 or Ethernet2-3/1-48
#       - Ethernet4
#     description: Leaf1_Trunk_eth4
#     profile: int_trunk_host
#   - switches:
#       - s1-leaf[2]
#     switch_ports: # Ex Ethernet1-48 or Ethernet2-3/1-48
#       - Ethernet4
#     description: Leaf2_Access_eth4
#     profile: int_access_host




  

# servers:
#   - name: s1-host1
#     rack: pod1
#     adapters:
#       - endpoint_ports: [Eth1, Eth2]
#         switch_ports: [Ethernet4, Ethernet4]
#         switches: [s1-leaf1, s1-leaf2]
#         profile: TRUNK
#         port_channel:
#           description: PortChannel
#           mode: active

  # - name: s1-host2
  #   rack: pod2
  #   adapters:
  #     - endpoint_ports: [Eth1, Eth2]
  #       switch_ports: [Ethernet4, Ethernet4]
  #       switches: [s1-leaf3, s1-leaf4]
  #       profile: TRUNK
  #       port_channel:
  #         description: PortChannel
  #         mode: active

# Sample network port config as access ports
# For multiport port-channel setup, please use the connected endpoint example above