---
# Documentation
eos_designs_documentation:
  # Generate fabric-wide documentation.
  enable: true
  # Include connected endpoints in the fabric-wide documentation.
  connected_endpoints: true
  # Generate Topology CSV with all interfaces towards other devices.
  topology_csv: true
  # Generate P2P links CSV with all routed point-to-point links between devices.
  p2p_links_csv: true

# local user information
local_users:
  - name: test-admin
    privilege: 15
    role: network-admin
    sha512_password: "$6$7GTxsrRjnwheeKfR$zhJ8qycVjAJz41rf5JRSfWIzp93IL5WL7sMS/Taz1yfShz.MAnoajCf7R2n1/EZW7PN5QA3Huayl0lVQesBYN1"

# OOB Management network default gateway
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

name_servers:
  - 192.168.2.1
  - 8.8.8.8

ntp:
  servers:
  - name: time.google.com
    preferred: true
    vrf: default
    iburst: true

dns_domain: tsmc.com.tw
